"""
Hand-written shape-bucket heuristic for pretuned RoPE kernels.

Generated from:
  benchmarks/logs/rope_autotune_gpu1_20260511_190507/optimal_configs.json

The config dictionaries use exact TritonBench (hidden_size, seq_length) buckets
and fall back to the H8192_T2048 config when a shape is not in the table. The
TritonBench sweep includes H8192_T2048 twice; exact shape buckets intentionally
use the first result for that duplicate shape.
"""

from __future__ import annotations


_DEFAULT_SHAPE = (8192, 2048)

_FWD_CONFIGS_BY_SHAPE = {
  (512, 2048): {'atomic_indexing': [],
               'block_sizes': [1, 16],
               'indexing': ['tensor_descriptor',
                            'pointer',
                            'tensor_descriptor',
                            'pointer',
                            'tensor_descriptor',
                            'tensor_descriptor'],
               'l2_groupings': [1],
               'load_eviction_policies': ['', 'last', 'last', 'last'],
               'loop_orders': [[1, 0]],
               'num_stages': 2,
               'num_warps': 32,
               'pid_type': 'xyz',
               'range_flattens': [None],
               'range_multi_buffers': [None],
               'range_num_stages': [0],
               'range_unroll_factors': [0],
               'range_warp_specializes': []},
 (2048, 2048): {'atomic_indexing': [],
                'block_sizes': [1, 1],
                'indexing': ['tensor_descriptor',
                             'tensor_descriptor',
                             'pointer',
                             'pointer',
                             'tensor_descriptor',
                             'pointer'],
                'l2_groupings': [1],
                'load_eviction_policies': ['last', 'last', 'first', 'last'],
                'loop_orders': [[0, 1]],
                'num_stages': 1,
                'num_warps': 1,
                'pid_type': 'flat',
                'range_flattens': [None],
                'range_multi_buffers': [None],
                'range_num_stages': [0],
                'range_unroll_factors': [0],
                'range_warp_specializes': []},
 (8192, 1024): {'atomic_indexing': [],
                'block_sizes': [1, 1],
                'indexing': ['tensor_descriptor',
                             'pointer',
                             'tensor_descriptor',
                             'tensor_descriptor',
                             'tensor_descriptor',
                             'pointer'],
                'l2_groupings': [1],
                'load_eviction_policies': ['first', '', 'first', 'last'],
                'loop_orders': [[0, 1]],
                'num_stages': 2,
                'num_warps': 16,
                'pid_type': 'flat',
                'range_flattens': [None],
                'range_multi_buffers': [None],
                'range_num_stages': [0],
                'range_unroll_factors': [0],
                'range_warp_specializes': []},
 (8192, 2048): {'atomic_indexing': [],
                'block_sizes': [1, 1],
                'indexing': ['pointer',
                             'tensor_descriptor',
                             'pointer',
                             'pointer',
                             'pointer',
                             'tensor_descriptor'],
                'l2_groupings': [1],
                'load_eviction_policies': ['', '', '', ''],
                'loop_orders': [[1, 0]],
                'num_stages': 1,
                'num_warps': 16,
                'pid_type': 'flat',
                'range_flattens': [None],
                'range_multi_buffers': [None],
                'range_num_stages': [0],
                'range_unroll_factors': [0],
                'range_warp_specializes': []},
 (8192, 4096): {'atomic_indexing': [],
                'block_sizes': [1, 1],
                'indexing': ['tensor_descriptor',
                             'tensor_descriptor',
                             'tensor_descriptor',
                             'pointer',
                             'pointer',
                             'pointer'],
                'l2_groupings': [1],
                'load_eviction_policies': ['first', '', '', 'first'],
                'loop_orders': [[0, 1]],
                'num_stages': 1,
                'num_warps': 4,
                'pid_type': 'flat',
                'range_flattens': [None],
                'range_multi_buffers': [None],
                'range_num_stages': [0],
                'range_unroll_factors': [0],
                'range_warp_specializes': []},
 (8192, 8192): {'atomic_indexing': [],
                'block_sizes': [1, 1],
                'indexing': ['pointer',
                             'pointer',
                             'pointer',
                             'pointer',
                             'tensor_descriptor',
                             'pointer'],
                'l2_groupings': [1],
                'load_eviction_policies': ['', '', '', ''],
                'loop_orders': [[0, 1]],
                'num_stages': 1,
                'num_warps': 8,
                'pid_type': 'flat',
                'range_flattens': [None],
                'range_multi_buffers': [None],
                'range_num_stages': [0],
                'range_unroll_factors': [0],
                'range_warp_specializes': []},
 (8192, 16384): {'atomic_indexing': [],
                 'block_sizes': [1, 1],
                 'indexing': ['tensor_descriptor',
                              'pointer',
                              'pointer',
                              'pointer',
                              'pointer',
                              'pointer'],
                 'l2_groupings': [1],
                 'load_eviction_policies': ['', '', 'last', 'last'],
                 'loop_orders': [[0, 1]],
                 'num_stages': 1,
                 'num_warps': 4,
                 'pid_type': 'flat',
                 'range_flattens': [None],
                 'range_multi_buffers': [None],
                 'range_num_stages': [0],
                 'range_unroll_factors': [0],
                 'range_warp_specializes': []}}

_BWD_CONFIGS_BY_SHAPE = {
  (512, 2048): {'atomic_indexing': [],
               'block_sizes': [1, 16],
               'indexing': ['pointer',
                            'pointer',
                            'pointer',
                            'tensor_descriptor',
                            'tensor_descriptor',
                            'tensor_descriptor'],
               'l2_groupings': [64],
               'load_eviction_policies': ['first', '', 'last', 'last'],
               'loop_orders': [[0, 1]],
               'num_stages': 6,
               'num_warps': 32,
               'pid_type': 'flat',
               'range_flattens': [None],
               'range_multi_buffers': [None],
               'range_num_stages': [0],
               'range_unroll_factors': [0],
               'range_warp_specializes': []},
 (2048, 2048): {'atomic_indexing': [],
                'block_sizes': [1, 1],
                'indexing': ['pointer',
                             'pointer',
                             'tensor_descriptor',
                             'pointer',
                             'pointer',
                             'pointer'],
                'l2_groupings': [1],
                'load_eviction_policies': ['last', 'first', '', 'last'],
                'loop_orders': [[0, 1]],
                'num_stages': 3,
                'num_warps': 1,
                'pid_type': 'flat',
                'range_flattens': [None],
                'range_multi_buffers': [None],
                'range_num_stages': [0],
                'range_unroll_factors': [0],
                'range_warp_specializes': []},
 (8192, 1024): {'atomic_indexing': [],
                'block_sizes': [1, 1],
                'indexing': ['pointer',
                             'pointer',
                             'tensor_descriptor',
                             'pointer',
                             'pointer',
                             'pointer'],
                'l2_groupings': [1],
                'load_eviction_policies': ['last', 'first', 'first', 'last'],
                'loop_orders': [[0, 1]],
                'num_stages': 1,
                'num_warps': 16,
                'pid_type': 'flat',
                'range_flattens': [None],
                'range_multi_buffers': [None],
                'range_num_stages': [0],
                'range_unroll_factors': [0],
                'range_warp_specializes': []},
 (8192, 2048): {'atomic_indexing': [],
                'block_sizes': [1, 1],
                'indexing': ['pointer',
                             'pointer',
                             'pointer',
                             'pointer',
                             'pointer',
                             'pointer'],
                'l2_groupings': [1],
                'load_eviction_policies': ['first', '', '', 'first'],
                'loop_orders': [[0, 1]],
                'num_stages': 1,
                'num_warps': 4,
                'pid_type': 'flat',
                'range_flattens': [None],
                'range_multi_buffers': [None],
                'range_num_stages': [0],
                'range_unroll_factors': [0],
                'range_warp_specializes': []},
 (8192, 4096): {'atomic_indexing': [],
                'block_sizes': [1, 1],
                'indexing': ['pointer',
                             'pointer',
                             'pointer',
                             'pointer',
                             'pointer',
                             'pointer'],
                'l2_groupings': [1],
                'load_eviction_policies': ['', '', '', ''],
                'loop_orders': [[0, 1]],
                'num_stages': 1,
                'num_warps': 4,
                'pid_type': 'flat',
                'range_flattens': [None],
                'range_multi_buffers': [None],
                'range_num_stages': [0],
                'range_unroll_factors': [0],
                'range_warp_specializes': []},
 (8192, 8192): {'atomic_indexing': [],
                'block_sizes': [1, 1],
                'indexing': ['pointer',
                             'tensor_descriptor',
                             'tensor_descriptor',
                             'pointer',
                             'pointer',
                             'pointer'],
                'l2_groupings': [1],
                'load_eviction_policies': ['', '', '', ''],
                'loop_orders': [[0, 1]],
                'num_stages': 1,
                'num_warps': 2,
                'pid_type': 'flat',
                'range_flattens': [None],
                'range_multi_buffers': [None],
                'range_num_stages': [0],
                'range_unroll_factors': [0],
                'range_warp_specializes': []},
 (8192, 16384): {'atomic_indexing': [],
                 'block_sizes': [1, 1],
                 'indexing': ['pointer',
                              'pointer',
                              'pointer',
                              'pointer',
                              'pointer',
                              'pointer'],
                 'l2_groupings': [1],
                 'load_eviction_policies': ['last', 'last', 'last', 'last'],
                 'loop_orders': [[0, 1]],
                 'num_stages': 1,
                 'num_warps': 4,
                 'pid_type': 'xyz',
                 'range_flattens': [None],
                 'range_multi_buffers': [None],
                 'range_num_stages': [0],
                 'range_unroll_factors': [0],
                 'range_warp_specializes': []}}


def autotune_rope_fwd(hidden_size: int, seq_length: int) -> dict[str, object]:
    assert isinstance(hidden_size, int)
    assert isinstance(seq_length, int)
    shape = (hidden_size, seq_length)
    if shape in _FWD_CONFIGS_BY_SHAPE:
        return _FWD_CONFIGS_BY_SHAPE[shape]
    return _FWD_CONFIGS_BY_SHAPE[_DEFAULT_SHAPE]


def autotune_rope_bwd(hidden_size: int, seq_length: int) -> dict[str, object]:
    assert isinstance(hidden_size, int)
    assert isinstance(seq_length, int)
    shape = (hidden_size, seq_length)
    if shape in _BWD_CONFIGS_BY_SHAPE:
        return _BWD_CONFIGS_BY_SHAPE[shape]
    return _BWD_CONFIGS_BY_SHAPE[_DEFAULT_SHAPE]
